import Head from 'next/head';
import { Inter } from '@next/font/google';
import useData from '../hooks/useData';
import '../styles/Home.module.css';
import { TableData } from '../components/Table';
import { useState } from 'react';
import getType from './api/type';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	//USING CUSTOM HOOK
	const { dataAPI, setDataAPI } = useData();
	const [filterIndicator, setFilterIndicator] = useState('');

	const handleChange = e => {
		setFilterIndicator(e.target.value);
	};

	const handleSubmit = async e => {
		e.preventDefault();
		await getType(filterIndicator).then(data => setDataAPI(data));
	};

	if (!dataAPI) {
		return <div className='loader'>Cargando...</div>;
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='main-container'>
				<h1 className='title'>INDICADORES ECONÓMICOS</h1>
				<form className='input-container' onSubmit={handleSubmit}>
					<label htmlFor='name-indicator' className='label-input'>
						Ingrese el Codigo:
						<input
							type='text'
							className='input-text'
							id='name-indicator'
							value={filterIndicator}
							onChange={handleChange}
						/>
					</label>
					<label htmlFor='date-indicator' className='label-input'>
						Busqueda por fecha:
						<input className='input-text' type='date' id='date-indicator' />
					</label>
					<button className='btn-form' type='submit'>
						Buscar
					</button>
				</form>

				<TableData data={dataAPI} />
			</main>
		</>
	);
}
